import logo1 from '../../assets/defaultTeamLogos/logo1.jpg';
import logo2 from '../../assets/defaultTeamLogos/logo2.jpg';
import logo3 from '../../assets/defaultTeamLogos/logo3.jpg';

export const mockMatches = [
  {
    id: 1,
    status: 'Live',
    round: 'Quarter Finals',
    team1: { name: 'Diamond Kings', logo: logo1, score: 2 },
    team2: { name: 'Storm Dragons', logo: logo2, score: 1 },
    startTime: '03:30 PM',
    endTime: '04:00 PM',
    date: '2026-05-11',
    autoStopAt: '04:30 PM',
  },
  {
    id: 2,
    status: 'Upcoming',
    round: 'Quarter Finals',
    team1: { name: 'Diamond Kings', logo: logo1, score: 0 },
    team2: { name: 'Storm Dragons', logo: logo2, score: 0 },
    startTime: '03:30 PM',
    endTime: '04:00 PM',
    date: '2026-05-11',
    autoStartAt: '3:00 PM',
    autoStopAt: '4:30 PM',
  },
  {
    id: 3,
    status: 'Completed',
    round: 'Quarter Finals',
    team1: { name: 'Diamond Kings', logo: logo1, score: 1, winner: true },
    team2: { name: 'Storm Dragons', logo: logo2, score: 0, winner: false },
    startTime: '03:00 PM',
    endTime: '04:30 PM',
    date: '2026-05-11',
  },
  {
    id: 4,
    status: 'Upcoming',
    round: 'Semi Finals',
    team1: { name: 'Thunder Bears', logo: logo3, score: 0 },
    team2: { name: 'Ice Foxes', logo: logo1, score: 0 },
    startTime: '05:30 PM',
    endTime: '06:30 PM',
    date: '2026-05-12',
  },
  {
    id: 5,
    status: 'Completed',
    round: 'Round of 16',
    team1: { name: 'Thunder Bears', logo: logo3, score: 3, winner: true },
    team2: { name: 'Ocean Sharks', logo: logo2, score: 1, winner: false },
    startTime: '01:00 PM',
    endTime: '02:00 PM',
    date: '2026-05-10',
  },
  {
    id: 6,
    status: 'Completed',
    round: 'Round of 16',
    team1: { name: 'Ice Foxes', logo: logo1, score: 2, winner: true },
    team2: { name: 'Mountain Lions', logo: logo3, score: 0, winner: false },
    startTime: '02:00 PM',
    endTime: '03:00 PM',
    date: '2026-05-10',
  },
  {
    id: 7,
    status: 'Upcoming',
    round: 'Finals',
    team1: { name: 'TBD', logo: null, score: 0 },
    team2: { name: 'TBD', logo: null, score: 0 },
    startTime: '01:00 PM',
    endTime: '03:00 PM',
    date: '2026-05-15',
  }
];

export const mockRoundRobinMatches = [
  {
    id: 1,
    status: 'Live',
    round: 'Round 1',
    team1: { name: 'Diamond Kings', logo: logo1, score: 2 },
    team2: { name: 'Storm Dragons', logo: logo2, score: 1 },
    startTime: '03:30 PM',
    endTime: '04:30 PM',
    date: '2026-05-11',
    autoStopAt: '04:30 PM',
  },
  {
    id: 2,
    status: 'Upcoming',
    round: 'Round 1',
    team1: { name: 'Thunder Bears', logo: logo3, score: 0 },
    team2: { name: 'Ice Foxes', logo: logo1, score: 0 },
    startTime: '05:00 PM',
    endTime: '06:00 PM',
    date: '2026-05-11',
    autoStartAt: '05:00 PM',
    autoStopAt: '06:00 PM',
  },
  {
    id: 3,
    status: 'Completed',
    round: 'Round 1',
    team1: { name: 'Ocean Sharks', logo: logo2, score: 3, winner: true },
    team2: { name: 'Mountain Lions', logo: logo3, score: 1, winner: false },
    startTime: '01:00 PM',
    endTime: '02:00 PM',
    date: '2026-05-11',
  },
  {
    id: 4,
    status: 'Completed',
    round: 'Round 2',
    team1: { name: 'Diamond Kings', logo: logo1, score: 2, winner: true },
    team2: { name: 'Thunder Bears', logo: logo3, score: 0, winner: false },
    startTime: '01:00 PM',
    endTime: '02:00 PM',
    date: '2026-05-12',
  },
  {
    id: 5,
    status: 'Completed',
    round: 'Round 2',
    team1: { name: 'Storm Dragons', logo: logo2, score: 1, winner: false },
    team2: { name: 'Ice Foxes', logo: logo1, score: 2, winner: true },
    startTime: '03:00 PM',
    endTime: '04:00 PM',
    date: '2026-05-12',
  },
  {
    id: 6,
    status: 'Upcoming',
    round: 'Round 3',
    team1: { name: 'Diamond Kings', logo: logo1, score: 0 },
    team2: { name: 'Ocean Sharks', logo: logo2, score: 0 },
    startTime: '01:00 PM',
    endTime: '02:00 PM',
    date: '2026-05-13',
  },
  {
    id: 7,
    status: 'Upcoming',
    round: 'Round 3',
    team1: { name: 'Mountain Lions', logo: logo3, score: 0 },
    team2: { name: 'Ice Foxes', logo: logo1, score: 0 },
    startTime: '03:00 PM',
    endTime: '04:00 PM',
    date: '2026-05-13',
  },
];

export const mockGroupStandings = [
  {
    rank: 1,
    team: { name: 'Diamond Kings', logo: logo1 },
    played: 2,
    wins: 2,
    losses: 0,
    winRate: '100%',
  },
  {
    rank: 2,
    team: { name: 'Ice Foxes', logo: logo1 },
    played: 1,
    wins: 1,
    losses: 0,
    winRate: '100%',
  },
  {
    rank: 3,
    team: { name: 'Ocean Sharks', logo: logo2 },
    played: 1,
    wins: 1,
    losses: 0,
    winRate: '100%',
  },
  {
    rank: 4,
    team: { name: 'Storm Dragons', logo: logo2 },
    played: 2,
    wins: 0,
    losses: 2,
    winRate: '0%',
  },
  {
    rank: 5,
    team: { name: 'Thunder Bears', logo: logo3 },
    played: 1,
    wins: 0,
    losses: 1,
    winRate: '0%',
  },
  {
    rank: 6,
    team: { name: 'Mountain Lions', logo: logo3 },
    played: 1,
    wins: 0,
    losses: 1,
    winRate: '0%',
  },
];

export const mockScoringRounds = [
  { id: 'round1', label: 'Round 1', status: 'Completed' },
  { id: 'round2', label: 'Round 2', status: 'In Progress' },
  { id: 'round3', label: 'Round 3', status: 'Upcoming' },
];

export const mockScoringParticipants = [
  {
    rank: 1,
    name: 'Shadow_Ninja',
    status: 'Active',
    rounds: { round1: 410, round2: 420 },
    best: 420,
    total: 830,
  },
  {
    rank: 2,
    name: 'Sniper_God',
    status: 'Active',
    rounds: { round1: 410, round2: 420 },
    best: 420,
    total: 830,
  },
  {
    rank: 3,
    name: 'NoobMaster73',
    status: 'Active',
    rounds: { round1: 410, round2: 420 },
    best: 420,
    total: 830,
  },
  {
    rank: 4,
    name: 'LootGoblin',
    status: 'Active',
    rounds: { round1: 410, round2: 420 },
    best: 420,
    total: 830,
  },
  {
    rank: 5,
    name: 'ESRunner',
    status: 'Active',
    rounds: { round1: 410, round2: null },
    best: 410,
    total: 410,
  },
  {
    rank: 6,
    name: 'Ghost_Rider',
    status: 'Active',
    rounds: { round1: 410, round2: null },
    best: 410,
    total: 410,
  },
  {
    rank: 7,
    name: 'Headhunter',
    status: 'Eliminated',
    rounds: { round1: 410, round2: null },
    best: 410,
    total: 410,
  },
  {
    rank: 8,
    name: 'Camp_Master',
    status: 'Eliminated',
    rounds: { round1: 410, round2: null },
    best: 410,
    total: 410,
  },
];
